project:
  type: website
  output-dir: "."

website:
  title: "kai.do"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - portfolio.qmd
        
  page-footer:
    center: "Copyright © {{< now year >}} Kaido Analytics LLC"


format:
  html:
    theme: lumen
    css: styles.css
    toc: true



